### ISSUE TITLE
Add privacy manifest files

### ISSUE THREAD

**Issue by fujimo-t** [isaacadariku/flutter_native_badge#1]
I have been looking for a successor of [flutter_app_badger](https://pub.dev/packages/flutter_app_badger) since it seems to be dead.
I also found other plugin but I think this is better than others by following reasons:
* Modern and clean code (Implemented by swift and federated plugin's way)
* Not contains old and vendor specific Android implementation (I think it is useless for most developers and provided as non-endorsed federated plugin)

So I'm trying this plugin but I noticed that [Privacy Manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) not found.

Could you add the manifest files? (or creating merge request from me is better?)

**Comment by isaacadariku** [comment]
@fujimo-t thanks for bringing this up.

**Comment by fujimo-t** [comment]
Thank you for the quick response and also deps update!
I'll try it.
